export type Delivery = {
    deliveryId: number;
    userId: number;
    displayName: string;
    firstName: string;
    secondName: string;
    nationalId: string;
    nationalName: string;
    drivingLicenseExpiredDate: string;
    drivingLicenseNumber: string;
    licenseExpiredDate: string;
    licenseNumber: string;
    email: string;
    isEmailVerified: boolean;
    isActive: boolean;
    totalOrders: number;
    receivedBalance: number;
    withdrawalBalance: number;
    vehiclePhotoFileUrl: string;
    drivingLicenseFileUrl: string;
    vehicleLicenseFileUrl: string;
    nationalIqamaIDFileUrl: string;
    isRejected: boolean;
    isAccepted: boolean;
  };