export interface OrderDetails {
    id: number,
    orderStatus: "ORDER PLACED" | "PREPARING" | "SHIPPED" | "CANCELED" | "COMPLETED",
    totalPrice: number,
    date: Date,
    transactionId: string,
    paymentType: 1 | 2,
    isPaid: boolean,
    itemsPrice: number,
    systemFee: number,
    deliveryFee: number,
    specialRequest: string,
    customer: number,
    customerLocation: number,
    customerInformationId: number,
    provider: number,
    providerLocation: number,
    providerInformationId: number,
    delivery: number,
    deliveryInformationId: number,
    customerLocationName: string,
    customerLocationLatitude: number,
    customerLocationLongitude: number,
    providerLocationName: string,
    providerLocationLatitude: number,
    providerLocationLongitude: number,
    customerDisplayName: string,
    providerDisplayName: string,
    deliveryDisplayName: string,

}