export interface OrderOfferItem {
    id: number,
    order: number,
    productOffer: number,
    quantity: number,
    unitPrice: number,
    productId: number,
    productImageUrl: string,
    productIsActive: boolean,
    productMeasurementUnit: string,
    productDescription: string,
    productName: string,
    productCategoryId: number,
    productCategoryIsActive:  boolean,
    productCategoryName: string,
}