export type ProviderProfile = {
    id: number,
    firstName: string,
    secondName: string,
    nationalApprovalId: string,
    companyName: string,
    ownerName: string,
    ownerNationalId: string,
    ownershipDocumentFileUrl: string,
    ownerNationalApprovalFileUrl: string,
    locationName: string,
    longitude: number,
    latitude: number,
    buildingType: string,
    buildingNumber: string,
    floorNumber: string,
    apartmentNumber: string,
    city?: string,
    streetNumber: string,
    phoneNumber: string,
    isAccepted: boolean,
    isRejected: boolean,
    submitDate: Date,
    reviewDate: Date | null,
    providerId: number,
    isActive: boolean,
    reviewDescription: string | null
  }