export type WithdrawRequest = {
    id: number;
    partyDisplayName: string;
    deliveryId: number | null;
    providerId: number | null;
    activeBalanceReceives: number;
    activeBalanceDeductions: number;
    bankAccountNumber: string;
    iBanNumber: string;
    date: Date;
    done: boolean;
    accepted: boolean;
    rejected: boolean;
    accountName: string | null;
    accountNumber: string | null;
    amount: number;
    swiftCode: string | null;
    bankName: string | null;
    partyIsActive: boolean;
};